### PR TITLE
fix(image/build): Extend image pulling timeout

### PR DESCRIPTION
**Pull request by sbusso**
CE-158 & CE-159

### CODE REVIEW

**Review by itsconquest — CHANGES_REQUESTED** [review]
This timeout is not enough, there are still many cases where operations fail for me:

**Image push:**
1.7GB image (based on codait/max-object-detector:latest): failure
15GB image (based on nvcr.io/nvidia/tensorflow:20.12-tf1-py3): failure

**Image pull:**
1.7GB image (codait/max-object-detector:latest): success
15GB image (nvcr.io/nvidia/tensorflow:20.12-tf1-py3): failure

**Image export:**
1.7GB image (codait/max-object-detector:latest): success
15GB image (nvcr.io/nvidia/tensorflow:20.12-tf1-py3): failure

**Image import:**
1.7GB image (codait/max-object-detector:latest): failure
15GB image (nvcr.io/nvidia/tensorflow:20.12-tf1-py3): failure

**Image build:**
1.7GB image (based on codait/max-object-detector:latest): failure
15GB image (based on nvcr.io/nvidia/tensorflow:20.12-tf1-py3): failure

**Comment by mcpacino** [comment]
I increase the timeout to 3000 seconds for testing does it matter

**Comment by huib-portainer** [comment]
Close https://github.com/portainer/portainer/issues/3878

**Pull request merged**
