### PR TITLE
fix(code/security): vcs status error [EE-5062]

### PR DESCRIPTION
**Pull request by oscarzhou-portainer**
closes [EE-5062]

[EE-5062]: https://portainer.atlassian.net/browse/EE-5062?

### CODE REVIEW

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by oscarzhou-portainer — COMMENTED** [review]
/scan

**Review by yi-portainer — APPROVED** [review]

**Pull request merged**
