### PR TITLE
Feat 170 kubectl bin

### LINKED ISSUE #170: add kubectl binary to image and API bindings
related to https://github.com/portainer/portainer/issues/4321

this issue requires :
- downloading the kubectl binary (add to setup.sh)
- adding it to the image
- add API bindings to deploy an application using this kubectl binary

### PR DESCRIPTION
**Pull request by mcpacino**
close #170

### CODE REVIEW

**Comment by deviantony** [comment]
@mcpacino do you mind rebasing it?

Also is it normal that the CI is failing for this build?

**Comment by ssbkang** [comment]
@mcpacino nothing biggie but could we relocate `download_docker_binary.sh` and `download_kubectl_binary.sh` scripts under the `build` directory. Just because that both are used for both Linux and Windows

**Review by deviantony — COMMENTED** [review]
Portainer associated feature request LGTM via https://github.com/portainer/portainer/pull/4866#pullrequestreview-609228009

**Pull request merged**
