### PR TITLE
feat(build): upgrade docker version

### LINKED ISSUE #158: Upgrade Docker binary to version >19.03.2
Following https://github.com/portainer/portainer/issues/3206

We need to update the binary embedded in the agent to support the deployment of Edge stacks using latest Compose format.

As a part of this issue, we'll also need to ensure that the Windows binary is injected during image build (it had to be manually injected for the last release) so we'll need to update our CI to support this.

### PR DESCRIPTION
**Pull request by chiptus**
fix #158

### CODE REVIEW

**Comment by deviantony** [comment]
We can't review the images built through the CI pipeline as the pipeline is hardcoding the download of the Docker binary (not using `setup.sh` script). We'll need to update our CI pipeline to proceed with that one.

**Comment by mcpacino** [comment]
I have updated the Agent CI. 
All Linux jobs download docker by calling the setup.sh 
Windows job can not run the bash script so I updated the script with the new URL.

**Review by deviantony — APPROVED** [review]
LGTM

Tested via `portainerci/agent:docker-version`, see my review with Portainer in https://github.com/portainer/portainer/pull/4333#pullrequestreview-556061944

**Review by sbusso — APPROVED** [review]

**Comment by itsconquest** [comment]
@chiptus could you please rebase this on the latest develop branch?

**Comment by chiptus** [comment]
@itsconquest done

**Review by itsconquest — APPROVED** [review]
LGTM!

**Pull request merged**
